kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Maven Central Publishing
SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=true
SONATYPE_CONNECT_TIMEOUT_SECONDS=60
SONATYPE_CLOSE_TIMEOUT_SECONDS=900

# POM Metadata
POM_URL=https://github.com/JoFre20/appwrite-kmp
POM_SCM_URL=https://github.com/JoFre20/appwrite-kmp
POM_SCM_CONNECTION=scm:git:git://github.com/JoFre20/appwrite-kmp.git
POM_SCM_DEV_CONNECTION=scm:git:git://github.com/JoFre20/appwrite-kmp.git
POM_LICENCE_NAME=The MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=jofre20
POM_DEVELOPER_NAME=Jonte Walter
POM_DEVELOPER_URL=https://github.com/JoFre20/
POM_DEVELOPER_EMAIL=j.walter@socialhope.app

# Publishing checksums
systemProp.org.gradle.internal.publish.checksums.insecure=true
systemProp.org.gradle.internal.http.socketTimeout=120000
